local counter = 0

function init(self)
	msg.post(".", "acquire_input_focus") -- <1>
	counter = 0;
	print(counter)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("click!")
		local button = gui.get_node("button")
		if gui.pick_node(button, action.x, action.y) then
			counter = counter + 1
			print(counter)
		else
			print ("You did not click on box")
		end
	end
end
